version: 2

models:
  - name: fact_home_team_rosters
    description: "每场比赛主场球队的球员名单"
    columns:
      - name: game_id
        tests:
          - not_null
      - name: player_id
        tests:
          - not_null

models:
  - name: fct_player_stats
    description: "这是我们的核心事实表，记录了每位球员每场比赛的表现和胜负结果。"
    columns:
      - name: player_id
        description: "球员的唯一标识符，来自 seed nba_players"
        tests:
          - not_null

      - name: is_win
        description: "胜负核心指标。1 代表赢，0 代表输。逻辑：(主队且主胜) 或 (客队且客胜)。"
        tests:
          - not_null
          - accepted_values:
              values: [0, 1]

models:
  - name: mart_player_leaderboard
    description: "球员胜率排行榜"
    columns:
      - name: player_name      # <--- 这里改成 player_name
        description: "球员姓名"
        tests:
          - unique             # 在这个榜单里，名字必须是唯一的
          - not_null
      
      - name: win_percentage
        tests:
          - not_null